// Generated by gencpp from file mover_arm_joints/move_and_confirmResponse.msg
// DO NOT EDIT!


#ifndef MOVER_ARM_JOINTS_MESSAGE_MOVE_AND_CONFIRMRESPONSE_H
#define MOVER_ARM_JOINTS_MESSAGE_MOVE_AND_CONFIRMRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace mover_arm_joints
{
template <class ContainerAllocator>
struct move_and_confirmResponse_
{
  typedef move_and_confirmResponse_<ContainerAllocator> Type;

  move_and_confirmResponse_()
    {
    }
  move_and_confirmResponse_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> const> ConstPtr;

}; // struct move_and_confirmResponse_

typedef ::mover_arm_joints::move_and_confirmResponse_<std::allocator<void> > move_and_confirmResponse;

typedef boost::shared_ptr< ::mover_arm_joints::move_and_confirmResponse > move_and_confirmResponsePtr;
typedef boost::shared_ptr< ::mover_arm_joints::move_and_confirmResponse const> move_and_confirmResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace mover_arm_joints

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "mover_arm_joints/move_and_confirmResponse";
  }

  static const char* value(const ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct move_and_confirmResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::mover_arm_joints::move_and_confirmResponse_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // MOVER_ARM_JOINTS_MESSAGE_MOVE_AND_CONFIRMRESPONSE_H
