// Generated by gencpp from file mover_arm_joints/move_and_confirm.msg
// DO NOT EDIT!


#ifndef MOVER_ARM_JOINTS_MESSAGE_MOVE_AND_CONFIRM_H
#define MOVER_ARM_JOINTS_MESSAGE_MOVE_AND_CONFIRM_H

#include <ros/service_traits.h>


#include <mover_arm_joints/move_and_confirmRequest.h>
#include <mover_arm_joints/move_and_confirmResponse.h>


namespace mover_arm_joints
{

struct move_and_confirm
{

typedef move_and_confirmRequest Request;
typedef move_and_confirmResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct move_and_confirm
} // namespace mover_arm_joints


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::mover_arm_joints::move_and_confirm > {
  static const char* value()
  {
    return "d3996e189f231d649f823398a7475c7d";
  }

  static const char* value(const ::mover_arm_joints::move_and_confirm&) { return value(); }
};

template<>
struct DataType< ::mover_arm_joints::move_and_confirm > {
  static const char* value()
  {
    return "mover_arm_joints/move_and_confirm";
  }

  static const char* value(const ::mover_arm_joints::move_and_confirm&) { return value(); }
};


// service_traits::MD5Sum< ::mover_arm_joints::move_and_confirmRequest> should match
// service_traits::MD5Sum< ::mover_arm_joints::move_and_confirm >
template<>
struct MD5Sum< ::mover_arm_joints::move_and_confirmRequest>
{
  static const char* value()
  {
    return MD5Sum< ::mover_arm_joints::move_and_confirm >::value();
  }
  static const char* value(const ::mover_arm_joints::move_and_confirmRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::mover_arm_joints::move_and_confirmRequest> should match
// service_traits::DataType< ::mover_arm_joints::move_and_confirm >
template<>
struct DataType< ::mover_arm_joints::move_and_confirmRequest>
{
  static const char* value()
  {
    return DataType< ::mover_arm_joints::move_and_confirm >::value();
  }
  static const char* value(const ::mover_arm_joints::move_and_confirmRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::mover_arm_joints::move_and_confirmResponse> should match
// service_traits::MD5Sum< ::mover_arm_joints::move_and_confirm >
template<>
struct MD5Sum< ::mover_arm_joints::move_and_confirmResponse>
{
  static const char* value()
  {
    return MD5Sum< ::mover_arm_joints::move_and_confirm >::value();
  }
  static const char* value(const ::mover_arm_joints::move_and_confirmResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::mover_arm_joints::move_and_confirmResponse> should match
// service_traits::DataType< ::mover_arm_joints::move_and_confirm >
template<>
struct DataType< ::mover_arm_joints::move_and_confirmResponse>
{
  static const char* value()
  {
    return DataType< ::mover_arm_joints::move_and_confirm >::value();
  }
  static const char* value(const ::mover_arm_joints::move_and_confirmResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MOVER_ARM_JOINTS_MESSAGE_MOVE_AND_CONFIRM_H
